version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/myapp

hooks:
  BeforeInstall:
    - location: scripts/clean.sh
      timeout: 300
      runas: ubuntu

  AfterInstall:
    - location: scripts/script.sh
      timeout: 600
      runas: ubuntu
