version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html

hooks:
  BeforeInstall:
    - location: scripts/script.sh
      timeout: 300
      runas: ubuntu

  # AfterInstall:
  #   - location: scripts/build_and_run_docker.sh
  #     timeout: 600
  #     runas: ec2-user
